# -*- coding: utf-8 -*-
"""김소현_2116504.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UTNFYS2nmTpM7yb25NB-DY22H3j60tMe

## 주의사항 1: 제출은 (이름)_(학번).py 파일로 저장하여 제출하시오. (예시: 허승휘_12345678.py) 
<U>_**ipynb 파일이 아닌 .py 파일입니다. 기말고사 영상을 참고하시기 바랍니다.**_<U>
    
## 주의사항 2: 함수 return 값들로 자동채점이 되기 때문에 기말고사 응시 전 함수강의를 잘 숙지하고 응시하시기 바랍니다.

## 주의사항 3: 늦은 제출은 허용되지 않습니다.

## 추가적인 주의사항들은 기말고사 영상을 참고하시기 바랍니다. (12월 8일 (목요일) 중에 공유 될 예정입니다)

# 1. 다음 question1() 함수를 이용해 입력 받은 두 값을 더하고자 한다. 코드를 실행시켜 a, b 값을 입력하고 함수를 이용해 결과를 받고자 할 때, return 받아야 할 값을 적으시오(add, subtract, multiply, div 중 택1).
"""

def question1(a,b):
    add = a+b
    subtract = a-b
    multiply = a*b
    div = a/b
    return add          # 왼쪽에 주어진 문제의 리턴값을 적어주세요 (add, subtract, multiply, div 중 1)

# 채점용 코드 입니다. 밑의 코드는 수정하지 마세요.
if __name__ == "__main__":
    print("1번함수는 a값과 b값을 더하는 함수 입니다. 각각의 값을 따로 입력해 주세요. \n")
    one = int(input('a 값을 입력하세요: '))
    two = int(input('b 값을 입력하세요: '))
    print(question1(one,two))

"""# 2. 다음 question2() 함수를 이용해 입력 받은 두 값을 곱하고자 한다. 코드를 실행시켜 a, b 값을 입력하고 함수를 이용해 결과를 받고자 할 때, return 받아야 할 값을 적으시오(add, subtract, multiply, div 중 택1)."""

def question2(a,b):
    add = a+b
    subtract = a-b
    multiply = a*b
    div = a/b
    return multiply           # 왼쪽에 주어진 문제의 리턴값을 적어주세요 (add, subtract, multiply, div 중 1)

# 채점용 코드 입니다. 밑의 코드는 수정하지 마세요.
if __name__ == "__main__":
    print("2함수는 a값과 b값을 곱하는 함수 입니다. 각각의 값을 따로 입력해 주세요. \n")
    a = int(input('a 값을 입력하세요: '))
    b = int(input('b 값을 입력하세요: '))
    print(question2(a,b))

"""# 3. 다음 question3() 함수를 이용해 사용자가 입력한 알파벳이 sentence의 몇 번째 문자열에 존재하는지 판별하는 프로그램을 작성하시오. 존재하지 않을 경우 '문장에 존재하지 않습니다' 를 반환하시오."""

def question3(letter):
    sentence = 'Korea qualified to knockout stage'
    num = 0
    found_it = False
#################################################################    
# 여기에 답안을 작성해 주세요. 다른 코드는 수정하지 마세요 #

    list_sentence = list(sentence)
    if user_input in list_sentence:
       while list_sentence[num] != user_input:
         num = num+1
       num = num+1
       found_it = True

#################################################################  
    if found_it:
        return '%d 번째에 존재합니다' %num
    else: 
        return '문장에 존재하지 않습니다'
# 채점용 코드 입니다. 밑의 코드는 수정하지 마세요.
if __name__ == "__main__":
    user_input = str(input('찾고 싶은 알파벳을 입력하세요.'))
    print(question3(user_input))

"""# 4. 다음 add(), subtract(), multi(), div() 함수를 이용하여 각 문제에 답하시오."""

# 4번문제에 필요한 함수들입니다. 필요할 때 활용하세요.
def add(a,b):
    return a+b
def subtract(a,b):
    return a-b
def multi(a,b):
    return a*b
def div(a,b):
    return a/b

# 1. 자신의 이름과 학번이 포함된 딕셔너리를 만들어 변수 student에 넣으시오
student = {'name':"김소현", 'number':2116504}

# 2. 만든 딕셔너리에 학년 항을 추가하시오
student['grade'] = 2


# 3. 위 함수를 이용하여 학생의 학번에 학년을 곱한 결과를 출력하시오. 반드시 함수를 이용하여 계산해야 함
st_num = student['number']
st_gr = student['grade']
result = multi(st_num, st_gr)
print(student['number'], result)

"""# 5. 사용자가 입력한 문자열에 동일한 두 문자가 연속되면 True, 그렇지 않으면 False를 반환하는 함수를 작성하시오."""

# letters 안에 동일한 문자가 붙어있다면 True 없다면 False 값을 반환하는 함수를 작성하시오.
# 예시 1) 'aa' -> True
# 예시 2) 'abc' -> False
# 예시 3) 'aba' -> False
# 예시 4) 'acebesad12312311' -> True

def question5(letters):
    same = False
#################################################################    
# 여기에 답안을 작성해 주세요. 다른 코드는 수정하지 마세요 #

    num = 0
    list_input = list(user_input)
    for i in range(len(list_input)):
       if list_input[num] == list_input[num+1] :
          same = True
          break
       else:
          num = i

#################################################################
    return same

if __name__ == "__main__":
    user_input = str(input('5번 함수에 들어갈 문자열을 넣어주세요: '))
    print(question5(str(user_input)))